# Generated by Django 2.1 on 2019-04-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectquestions',
            name='analyzations',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='selectquestions',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
