# Generated by Django 2.1 on 2019-05-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_questionnote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentanswers',
            options={'verbose_name': '文本题回答', 'verbose_name_plural': '文本题回答'},
        ),
        migrations.AlterModelOptions(
            name='contentquestion',
            options={'verbose_name': '文本题问题', 'verbose_name_plural': '文本题问题'},
        ),
        migrations.AlterModelOptions(
            name='normalanswers',
            options={'verbose_name': '讨论区回答', 'verbose_name_plural': '讨论区回答'},
        ),
        migrations.AlterModelOptions(
            name='normalquestions',
            options={'verbose_name': '讨论区问题', 'verbose_name_plural': '讨论区问题'},
        ),
        migrations.AlterModelOptions(
            name='questionnote',
            options={'verbose_name': '选择题笔记', 'verbose_name_plural': '选择题笔记'},
        ),
        migrations.AlterModelOptions(
            name='selectanswers',
            options={'verbose_name': '闯关选择题回答', 'verbose_name_plural': '闯关选择题回答'},
        ),
        migrations.AlterModelOptions(
            name='selectquestions',
            options={'verbose_name': '闯关选择题', 'verbose_name_plural': '闯关选择题'},
        ),
    ]
