# Generated by Django 2.1 on 2019-05-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(default='')),
                ('type', models.IntegerField(blank=True, default=0)),
                ('score', models.IntegerField(blank=True, default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
