# Generated by Django 2.1 on 2019-05-04 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='type',
        ),
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 11, 24, 53, 750068)),
        ),
        migrations.AddField(
            model_name='course',
            name='interview_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 11, 24, 53, 750048)),
        ),
        migrations.AddField(
            model_name='course',
            name='room',
            field=models.IntegerField(default=0),
        ),
    ]
