# Generated by Django 2.1 on 2019-05-22 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20190521_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
                ('selector_id', models.IntegerField()),
                ('teacher_id', models.IntegerField()),
                ('score', models.IntegerField()),
                ('content', models.TextField()),
                ('status', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 11, 30, 58, 881773)),
        ),
        migrations.AlterField(
            model_name='course',
            name='interview_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 11, 30, 58, 881754)),
        ),
    ]
