# Generated by Django 2.1 on 2019-05-28 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20190525_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '小老师课程', 'verbose_name_plural': '小老师课程'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name': '小老师课程类别', 'verbose_name_plural': '小老师课程类别'},
        ),
        migrations.AlterModelOptions(
            name='coursefeedback',
            options={'verbose_name': '小老师课程反馈', 'verbose_name_plural': '小老师课程反馈'},
        ),
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 28, 16, 48, 26, 294388)),
        ),
        migrations.AlterField(
            model_name='course',
            name='interview_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 28, 16, 48, 26, 294365)),
        ),
    ]
