# Generated by Django 2.1 on 2019-04-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.IntegerField(default=0, verbose_name='类型'),
        ),
    ]
