# Generated by Django 2.1 on 2019-04-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NormalOperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('answer_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('score', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SelectOperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('answer_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('score', models.IntegerField(blank=True, default=0)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
    ]
