# Generated by Django 2.1 on 2019-05-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='content',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
