# Generated by Django 2.1 on 2019-05-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomations', '0002_information_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='information',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
