# Generated by Django 2.1 on 2019-05-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infomations', '0003_auto_20190510_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name': '邀约讲解', 'verbose_name_plural': '邀约讲解'},
        ),
        migrations.AlterModelOptions(
            name='informationcomment',
            options={'verbose_name': '邀约讲解评论', 'verbose_name_plural': '邀约讲解评论'},
        ),
    ]
